final/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('online/',include('online_quizz.urls')),
]

online_quizz/urls.py
from django.urls import path
from . import views
app_name = "online_quizz"
urlpatterns = [
    path('home', views.home_page, name='home_page'),
    path('login',views.login_view,name='login'),
    path('register',views.register_page,name='register_page'),
    path('courses/', views.course_list, name='course_list'),
    path('details/<int:pk>/', views.course_detail, name='course_detail'),
    path('evaluate/<int:course_id>/', views.evaluate_results, name='evaluate_results'),
    path('logout', views.logout_, name='logout'),
    path('dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('gradebook/', views.gradebook, name='gradebook'),
    path('teacher-view/', views.teacher_view, name='teacher_view'),
    path('teacher/courses/', views.teacher_courses, name='teacher_courses'),
    path('teacher/course/<int:course_id>/', views.course_details, name='course_details'),
    path('teacher/course/add/', views.add_course, name='add_course'),
    path('teacher/course/update/<int:course_id>/', views.update_course, name='update_course'),
    path('teacher/course/delete/<int:course_id>/', views.delete_course, name='delete_course'),
    path('teacher/course/<int:course_id>/question/add/', views.add_question, name='add_question'),
    path('teacher/course/<int:course_id>/question/delete/<int:question_id>/', views.delete_question, name='delete_question'),
    path('courses/<int:course_id>/questions/<int:question_id>/update/', views.update_question, name='update_question'),

]

online_quizz/models.py
from django.db import models
from django.contrib.auth.models import Group

# Create your models here.
from django.contrib.auth.models import User

class Course(models.Model):
   course_name = models.CharField(max_length=50)
   description = models.CharField(max_length=200)
   total_marks = models.PositiveIntegerField()
   category = models.CharField(max_length=20, choices=(('Technical', 'Technical'), ('Non-Technical', 'Non-Technical')))
   def __str__(self):
        return f'{self.course_name},{self.description}' 

class Question(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    marks=models.PositiveIntegerField()
    question_number = models.IntegerField(default=1)
    question=models.CharField(max_length=600)
    option1=models.CharField(max_length=200)
    option2=models.CharField(max_length=200)
    option3=models.CharField(max_length=200)
    option4=models.CharField(max_length=200)
    cat=(('Option1','Option1'),('Option2','Option2'),('Option3','Option3'),('Option4','Option4'))
    answer=models.CharField(max_length=200,choices=cat)

class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=1)
    exam = models.ForeignKey(Course, on_delete=models.CASCADE)
    marks = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)
    percentage = models.FloatField()


    def __str__(self):
        return f"Result for {self.exam.course_name}"

online_quizz/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import  authenticate,login,logout
from django.contrib.auth.decorators import login_required ,permission_required
from django.contrib.auth.models import User, Group
from .models import Course,Question,Result
from django.contrib import messages

def home_page(request):
    return render(request,"online_quizz/main.html")

def login_view(request):
    error_message = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(password)
        print(username)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            # user_ = customer.objects.get(user=user)
            teacher = Group.objects.get(name='teachers')
            student = Group.objects.get(name='students')
            if teacher in user.groups.all():
                #redirect to teacher homepage
                return redirect('online_quizz:teacher_dashboard')
            if student in user.groups.all():
                #redirect to student homepage
                return  redirect('online_quizz:course_list')
            return redirect('online_quizz:home_page',)
            # print(username,password,user.id)
        else:
            error_message = 'Invalid login credentials'
    return render(request,'online_quizz/login.html',{'error_message':error_message})
# def register_page(request): 
#     error_message = ''
#     if request.method == "POST":
#         username_ = request.POST.get('username','')
#         email_ = request.POST.get('email','')
#         password_ = request.POST.get('password','')
#         confirm_password_ = request.POST.get('confirm_password','')
#         if password_ == confirm_password_:
#             if len(User.objects.filter(username=username_)) > 0:
#                 return redirect('online_quizz:register_page')
#             else:
#                 if len(User.objects.filter(email=email_)) > 0:
#                     return redirect('online_quizz:register_page')
#                 else:
#                     user = User.objects.create_user(username=username_, email=email_)
#                     user.set_password(password_)
#                     user.save()
#                     messages.success = (request,'Registration successful! You can now log in.')
#                     return redirect('online_quizz:home_page')
#         else:
#             error_message = 'Password and confirm password do not match.'
      
#     return render(request, 'online_quizz/register.html',  {'error_message': error_message})

def register_page(request):
    if request.method == "POST":
        username_ = request.POST.get('username', '')
        email_ = request.POST.get('email', '')
        password_ = request.POST.get('password', '')
        confirm_password_ = request.POST.get('confirm_password', '')

        if password_ == confirm_password_:
            if User.objects.filter(username=username_).exists():
                messages.error(request, 'Username already exists. Please choose a different username.')
                return redirect('online_quizz:register_page')
            elif User.objects.filter(email=email_).exists():
                messages.error(request, 'Email already exists. Please enter a different email.')
                return redirect('online_quizz:register_page')
            else:
                user = User.objects.create_user(username=username_, email=email_)
                user.set_password(password_)
                user.save()
                messages.success(request, 'Registration successful! You can now log in.')
                return redirect('online_quizz:home_page')
        else:
            messages.error(request, 'Password and confirm password do not match.')
            return redirect('online_quizz:register_page')

    return render(request, 'online_quizz/register.html')
@permission_required('online_quizz.view_course',login_url='online_quizz:login')
def course_list(request):
    technical_courses = Course.objects.filter(category='Technical')
    non_technical_courses = Course.objects.filter(category='Non-Technical')
    return render(request, 'online_quizz/course_list.html', {'technical_courses': technical_courses, 'non_technical_courses': non_technical_courses})


@permission_required('online_quizz.view_question',login_url='online_quizz:login')
def course_detail(request, pk):
    course = Course.objects.get(pk=pk)
    questions = Question.objects.filter(course=course)
    return render(request, 'online_quizz/course_detail.html', {'course': course, 'questions': questions})

@permission_required('online_quizz.view_question',login_url='online_quizz:login')
def evaluate_results(request, course_id):
    if request.method == 'POST':
        course = get_object_or_404(Course, id=course_id)
        student_group = request.user.groups.first()
        student_answers = request.POST
        total_marks = 0
        obtained_marks = 0

        for question in course.question_set.all():
            question_id = str(question.id)
            selected_answer = student_answers.get(f"question_{question.id}")
            print(selected_answer)
            print(question.answer)
            if selected_answer == question.answer:
                obtained_marks += question.marks

            total_marks += question.marks

        percentage_value = (obtained_marks / total_marks) * 100

        result = Result.objects.create(user=request.user, group=Group.objects.get(name='students'), exam=course, marks=obtained_marks, percentage=percentage_value)
        return render(request, 'online_quizz/result.html', {'result': result, 'total_marks': total_marks, 'percentage': percentage_value})

    else:
        course = get_object_or_404(Course, id=course_id)
        questions = course.question_set.all()
        return render(request, 'online_quizz/course_detail.html', {'course': course, 'questions': questions})
def logout_(request):
    logout(request)
    return redirect('online_quizz:home_page')

@permission_required('online_quizz.view_dashboard',login_url='online_quizz:login')
def teacher_dashboard(request):

    students = User.objects.filter(groups__name='students')
    courses = Course.objects.all()
    student_count = students.count()
    course_count = Course.objects.count()
    context = {
        'students': students,
        'courses': courses,
        'student_count':student_count,
        'course_count':course_count,
        
    }

    return render(request, 'online_quizz/teacher_dashboard.html', context)

@permission_required('online_quizz.view_gradebook',login_url='online_quizz:login')
def gradebook(request):
    user_ = request.user
    results = Result.objects.filter(group__name='students', user=user_) # Filter results by group name 'students' and student

    quizzes_count = 0
    overall_percentage = 0.0

    for result in results:
        if result.percentage is not None:
            overall_percentage += result.percentage
            quizzes_count += 1

    overall_percentage = overall_percentage / quizzes_count if quizzes_count > 0 else 0.0

    profile_data = []
    for result in results:
        percentage = result.percentage if result.percentage is not None else 0.0
        total_marks = sum(question.marks for question in result.exam.question_set.all())

        profile_data.append({
            'course_name': result.exam.course_name,
            'marks': result.marks,
            'percentage': percentage,
            'date': result.date,
            'total_marks': total_marks
        })

    return render(request, 'online_quizz/gradebook.html', {'profile_data': profile_data, 'overall_percentage': overall_percentage})

@permission_required('online_quizz.view_student_profile',login_url='online_quizz:login')
def teacher_view(request):
    students = User.objects.filter(groups__name='students')  # Get all users in 'students' group
    student_data = []

    for student in students:
        results = Result.objects.filter(group__name='students', exam__in=Course.objects.all(), user=student)
        total_marks = sum(result.marks for result in results)
        quizzes_attempted = results.count()
        overall_percentage = (total_marks / (quizzes_attempted * 100)) * 100 if quizzes_attempted > 0 else 0

        student_data.append({
            'student': student,
            'results': results,
            'total_marks': total_marks,
            'quizzes_attempted': quizzes_attempted,
            'overall_percentage': overall_percentage,
        })

    return render(request, 'online_quizz/teacher_view.html', {'student_data': student_data})


@permission_required('online_quizz.view_teacher_course',login_url='online_quizz:login')
def teacher_courses(request):
    technical_courses = Course.objects.filter(category='Technical')
    non_technical_courses = Course.objects.filter(category='Non-Technical')
    return render(request, 'online_quizz/teacher_courses.html', {'technical_courses': technical_courses, 'non_technical_courses': non_technical_courses})

@permission_required('online_quizz.view_teacher_question',login_url='online_quizz:login')
def course_details(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    questions = course.question_set.all()
    return render(request, 'online_quizz/course_details.html', {'course': course, 'questions': questions})

@permission_required('online_quizz.add_course',login_url='online_quizz:login')
def add_course(request):
    if request.method == 'POST':
        # Process form data and save the new course
        course_name = request.POST['course_name']
        description = request.POST['description']
        total_marks = request.POST['total_marks']
        category = request.POST['category']

online_quizz/templates/online_quizz/add_course.html
{% extends 'online_quizz\dashborad_base.html' %}
{% block link %}
  <link rel="stylesheet" href="/static/css/add_course.css" >
{% endblock %}
{% block title %}
  Add course
{% endblock %}
{% block content %}
    {% load static %}
    <h1>Add Course</h1>
    <form method="post">
        {% csrf_token %}
        <label for="course_name">Course Name:</label>
        <input type="text" name="course_name" id="course_name">
        
        <label for="description">Description:</label>
        <textarea name="description" id="description"></textarea>
        
        <label for="total_marks">Total Marks:</label>
        <input type="number" name="total_marks" id="total_marks">

        <label for="total_marks">category:</label>
        <input type="text" name="category" id="category">
        
        <button type="submit">Add Course</button>
    </form>
{% endblock %}

online_quizz/templates/online_quizz/add_question.html
<!DOCTYPE html>
	<html>
		<head>
			<title>add question</title>
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
			<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
			<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
			<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
			<link rel="stylesheet" href="/static/css/add_question.css" />
		<!------ Include the above in your HEAD tag ---------->
		</head>
		<body>
			<header>
				<h1>Online Quizz</h1>
				{% if user.is_authenticated %}
					<div class="user-container">
						<div class="dropdown">
							<button onclick="toggleDropdown()" class="dropbtn">{{ user.username }}   <i class="fa-solid fa-user"></i></button>
							<div id="dropdown-content" class="dropdown-content">
								<a href="{% url 'online_quizz:logout'%}">Logout</a>
							</div>
						</div>
					</div>
				{% else %}
					<div class="user-container">
						<a href="#" class="login-link">Login</a>
					</div>
				{% endif %}
			</header>
			<div class="container">
				<div class="row">
					<h1>Teacher Dashboard</h1>
					<hr/>
					
					<div id="wrapper">
					<!-- Sidebar -->
						<div id="sidebar-wrapper">
							<ul class="sidebar-nav" style="margin-left:0;">
								<li class="sidebar-brand">
									
									<a href="#menu-toggle"  id="menu-toggle" style="margin-top:20px;float:right;" > <i class="fa fa-bars " style="font-size:20px !Important;" aria-hidden="true" aria-hidden="true"></i> </a>
									
								</li>
								<li>
									<a href="{% url 'online_quizz:teacher_dashboard' %}"><i class="fa-solid fa-house-user"></i> <span style="margin-left:10px;">Dashboard</span>  </a>
								</li>
								<!-- <li>
									<a href="#"> <i class="fa fa-play-circle-o " aria-hidden="true"> </i> <span style="margin-left:10px;">courses</span> </a>
								</li> -->
								<!-- <li>
									<a href="#"> <i class="fa-solid fa-clipboard-question"></i> <span style="margin-left:10px;"> questions</span> </a>
								</li> -->
								<li>
									<a href="{% url 'online_quizz:teacher_courses' %}"> <i class="fa-solid fa-book"></i> <span style="margin-left:10px;"> courses</span> </a>
								</li>
								<!-- <li>
									<a href="#"><i class="fa fa-info-circle " aria-hidden="true"> </i> <span style="margin-left:10px;">Section </span> </a>
								</li> -->
								<li>
									<a href="#"> <i class="fa-solid fa-right-from-bracket"></i> <span style="margin-left:10px;"> logout</span> </a>
								</li>
							</ul>
						</div>
						<!-- /#sidebar-wrapper -->
				
						<!-- Page Content -->
						<h2>Add Question</h2>
						<form method="POST" action="{% url 'online_quizz:add_question' course_id=course.id %}">
							{% csrf_token %}
							<div class="form-group">
								<label for="question">Question:</label>
								<textarea class="form-control" id="question" name="question" rows="3"></textarea>
							</div>
							<div class="form-group">
								<label for="marks">Marks</label>
								<input type="number" class="form-control" id="marks" name="marks">
							</div>
							<div class="form-group">
								<label for="question_number">Question Number</label>
								<input type="text" class="form-control" id="question_number" name="question_number">
							</div>
							<div class="form-group">
								<label for="Option1">Option 1:</label>
								<input type="text" class="form-control" id="option1" name="Option1">
							</div>
							<div class="form-group">
								<label for="Option2">Option 2:</label>
								<input type="text" class="form-control" id="option2" name="Option2">
							</div>
							<div class="form-group">
								<label for="Option3">Option 3:</label>
								<input type="text" class="form-control" id="option3" name="Option3">
							</div>
							<div class="form-group">
								<label for="option4">Option 4:</label>
								<input type="text" class="form-control" id="option4" name="Option4">
							</div>
							<div class="form-group">
								<label for="answer">Answer:</label>
								<select class="form-control" id="answer" name="answer">
									<option value="Option1">Option 1</option>
									<option value="Option2">Option 2</option>
									<option value="Option3">Option 3</option>
									<option value="Option4">Option 4</option>
								</select>
							</div>
							<button id="submit-btn" type="submit" class="btn btn-primary submit-button">Submit</button>
						</form>
					</div>				 
					<script>
						$("#menu-toggle").click(function(e) {
							e.preventDefault();
							$("#wrapper").toggleClass("toggled");
						});
					</script>	
								
			
				
				</div>
			</div>
			

			<script>
				function toggleDropdown() {
					var dropdownContent = document.getElementById("dropdown-content");
					dropdownContent.classList.toggle("show");
				}
				
				window.onclick = function(event) {
					if (!event.target.matches('.dropbtn')) {
						var dropdowns = document.getElementsByClassName("dropdown-content");
						for (var i = 0; i < dropdowns.length; i++) {
							var openDropdown = dropdowns[i];
							if (openDropdown.classList.contains('show')) {
								openDropdown.classList.remove('show');
							}
						}
					}
				}
				
			</script>
			
		</body>
	</html>

online_quizz/templates/online_quizz/dashborad_base.html
<!DOCTYPE html>
	<html>
		<head>
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
			<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
			<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
			<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
			<link rel="stylesheet" href="/static/css/dashboard.css" />
			{% block link %}
			{% endblock %}
			<title>
				{% block title %}
				
				{% endblock %}
			</title>
			
		</head>
		<body>
			<header>
				<h1>Online Quizz</h1>
				{% if user.is_authenticated %}
					<div class="user-container">
						<div class="dropdown">
							<button onclick="toggleDropdown()" class="dropbtn">{{ user.username }}   <i class="fa-solid fa-user"></i></button>
							<div id="dropdown-content" class="dropdown-content">
								<a href="{% url 'online_quizz:logout'%}">Logout</a>
							</div>
						</div>
					</div>
				{% else %}
					<div class="user-container">
						<a href="#" class="login-link">Login</a>
					</div>
				{% endif %}
			</header>
			<div class="container">
				<div class="row">
					<h1>Teacher Dashboard</h1>
					<hr/>
					
					<div id="wrapper">
					
				
			
						<!-- Sidebar -->
						<div id="sidebar-wrapper">
							<ul class="sidebar-nav" style="margin-left:0;">
								<li class="sidebar-brand">
									
									<a href="#menu-toggle"  id="menu-toggle" style="margin-top:20px;float:right;" > <i class="fa fa-bars " style="font-size:20px !Important;" aria-hidden="true" aria-hidden="true"></i> </a>
								</li>
								<li>
									<a href="{% url 'online_quizz:teacher_dashboard' %}"><i class="fa-solid fa-house-user"></i> <span style="margin-left:10px;">Dashboard</span>  </a>
								</li>
								<li>
									<a href="{% url 'online_quizz:teacher_courses' %}"> <i class="fa-solid fa-book"></i> <span style="margin-left:10px;"> courses</span> </a>
								</li>
								<li>
									<a href="{% url 'online_quizz:logout' %}"> <i class="fa-solid fa-right-from-bracket"></i> <span style="margin-left:10px;"> logout</span> </a>
								</li>
							</ul>
						</div>
						<!-- /#sidebar-wrapper -->
				
						<!-- Page Content -->
						{% block content %}
						{% endblock %}
					</div>
									
					<script>
						$("#menu-toggle").click(function(e) {
							e.preventDefault();
							$("#wrapper").toggleClass("toggled");
						});
					</script>	
				</div>
			</div>
			<!-- <div class="footer">
				<footer>
					<div class="footer-container">
						<p>&copy; 2023 Online-Quizz</p>
						<div class="footer-icons">
							<a href="#"><i class="fab fa-facebook-f"></i></a>
							<a href="#"><i class="fab fa-twitter"></i></a>
							<a href="#"><i class="fab fa-instagram"></i></a>
							<a href="#"><i class="fab fa-linkedin-in"></i></a>
						</div>
					</div>
				</footer>
			</div> -->
			

			<script>
				function toggleDropdown() {
					var dropdownContent = document.getElementById("dropdown-content");
					dropdownContent.classList.toggle("show");
				}
				
				window.onclick = function(event) {
					if (!event.target.matches('.dropbtn')) {
						var dropdowns = document.getElementsByClassName("dropdown-content");
						for (var i = 0; i < dropdowns.length; i++) {
							var openDropdown = dropdowns[i];
							if (openDropdown.classList.contains('show')) {
								openDropdown.classList.remove('show');
							}
						}
					}
				}
				
			</script>
			
		</body>
	</html>

online_quizz/templates/online_quizz/delete_course.html
{% extends 'online_quizz/dashborad_base.html' %}
{% block link %}
  <link rel="stylesheet" href="/static/css/delete_course.css" >
{% endblock %}
{% block title %}
    Delete Courses
{% endblock %}
{% block content %}
    <h1>Delete Course</h1>
    <h3>Are you sure you want to delete the course "{{ course.course_name }}"?</h3>
    <form method="post">
        {% csrf_token %}
        <div class="container">
            <button type="submit">Delete</button><br>
            <div class="a"><a class="btn btn-success" href="{% url 'online_quizz:teacher_dashboard' %}">Cancel</a></div>
        </div>
       
    </form>
{% endblock %}

online_quizz/templates/online_quizz/delete_question.html
{% extends 'online_quizz\dashborad_base.html' %}
{% block title %}
    Delete Question
{% endblock %}
{% block content %}
    <h2>Delete Question</h2>
    <p>Are you sure you want to delete the following question?</p>
    <p>Question: {{ question.question }}</p>
    <p>Option 1: {{ question.option1 }}</p>
    <p>Option 2: {{ question.option2 }}</p>
    <p>Option 3: {{ question.option3 }}</p>
    <p>Option 4: {{ question.option4 }}</p>
    <p>Answer: {{ question.answer }}</p>
    <form method="POST" action="{% url 'online_quizz:delete_question' course_id=course.id question_id=question.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a href="{% url 'online_quizz:course_details' course_id=course.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

online_quizz/templates/online_quizz/gradebook.html
{% extends 'online_quizz/base.html' %}
{% block link %}
  <link rel="stylesheet" href="/static/css/gradebook.css" >
{% endblock %}
{% block title %}
    Gradebook
{% endblock %}
{% block content %}
    {% load static %}
    <h2 class="gradebook-title">Gradebook</h2>
    <p class="overall-percentage">Overall Percentage: {{ overall_percentage|floatformat:2 }}%</p>
    <table class="profile-table">
        <tr>
            <th>Course Name</th>
            <th>Obtained Marks</th>
            <th>Total Marks</th>
            <th>Percentage</th>
            <!-- <th>Date</th> -->
        </tr>
        {% for data in profile_data %}
        <tr>
            <td>{{ data.course_name }}</td>
            <td>{{ data.marks }}</td>
            <td>{{ data.total_marks }}</td>
            <td>{% if data.percentage %}{{ data.percentage|floatformat:2 }}%{% else %}N/A{% endif %}</td>
            <!-- <td>{{ data.date }}</td> -->
        </tr>
        {% endfor %}
    </table>
{% endblock %}

online_quizz/templates/online_quizz/teacher_courses.html
{% extends 'online_quizz/dashborad_base.html' %}
{% block link %}
  <link rel="stylesheet" href="/static/css/teacher_courses.css" >
{% endblock %}
{% block title %}
    Teacher Courses
{% endblock %}
{% block content %}
    <div class="card">
		<h2>Technical Courses</h2>
		<ul class="course-list">
			{% for course in technical_courses %}
				<li class="course-item">
					<h4>{{ course.course_name }}</h4>
					<a href="{% url 'online_quizz:course_details' course.id %}">Details</a>
				</li>
				<br>
			{% empty %}
				<li>No technical courses available.</li>
			{% endfor %}
		</ul>

		<h2>Non-Technical Courses</h2>
		<ul class="course-list">
			{% for course in non_technical_courses %}
				<li class="course-item">
					<h4>{{ course.course_name }}</h4>
					<a href="{% url 'online_quizz:course_details' course.id %}">Details</a>
				</li>
				<br>
			{% empty %}
				<li>No non-technical  courses available.</li>
			{% endfor %}
		</ul>
	</div>
    <ul>
        {% for course in courses %}
        <div class="course">
            <li>{{ course.course_name }} - </li>
        </div>
        {% endfor %}
    </ul>
    <div class="add">
        <a class="btn btn-success" href="{% url 'online_quizz:add_course' %}">Add Course</a>
    </div>
    
{% endblock %}
</body>

online_quizz/templates/online_quizz/teacher_dashboard.html
{% extends 'online_quizz\dashborad_base.html' %}
{% block link %}
  <link rel="stylesheet" href="/static/css/teacher_dashboard.css" >
{% endblock %}
{% block title %}
	Dashboard
{% endblock %}
{% block content %}
    {% load static %}
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-9">
                    <div class="objects">
                        <h2>Student Details</h2>
                        <p><a href="{% url 'online_quizz:teacher_view' %}">Total Students: {{ student_count }}</a></p>
                    </div>
                    <div class="objects">
                        <h2>Course Management</h2>
                        <p><a href="{% url 'online_quizz:teacher_courses' %}">Total Courses:{{ course_count }}</a></p>
                        <ul>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>	
{% endblock %}